###1
POST http://localhost:50535/boards
Content-Type: application/json

{
  "writer": "lee",
  "subject": "good news",
  "content": "Spring Data JPA에서 제공하는 JpaRepository 인터페이스를 상속하기만 해도 되며, 인터페이스에 따로 @Repository등의 어노테이션을 추가할 필요가 없다."
}

###2
POST http://localhost:8000/board-service/boards
Content-Type: application/json

{
  "writer": "kim",
  "subject": "bad news",
  "content": "정부가 양자·인공지능(AI)과 첨단 바이오를 '3대 게임체인저'로 지정하고, 성과 창출을 본격화한다. AI를 활용해 국민 삶의 질을 향상하는 사업에는 7천억원 넘는 돈을 투자한다.  양자인터넷 전송 거리를 연말까지 지금의 1천배(100㎞)로 늘리고, 과학기술의학전문대학원 신설도 추진한다."
}

###3
GET http://localhost:8000/board-service/boards

###4
GET http://localhost:8000/board-service/boards/4028b9f48dbc3545018dbc4a1f230003

###5
DELETE http://localhost:8000/board-service/boards/4028b9f48dc15421018dc154f0830000

###6
GET http://localhost:8000/board-service/boards/writer/kim

###7
POST http://localhost:8000/board-service/boards/recommendation
Content-Type: application/json

{
  "id": "4028b9f48dbadee2018dbae90f0a0000",
  "recommendationCount": -1
}