server:
  port: 0

spring:
  application:
    name: board-service
  jpa:
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 100
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  devtools:
    livereload:
      enabled: true
logging.level:
  org.hibernate.SQL: debug

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka